<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="UpdateEventTimestampWithSystemTime" Id="{1c17c617-9018-4ffd-b840-24e66e6e1447}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UpdateEventTimestampWithSystemTime
VAR_INPUT
	stEvent : REFERENCE TO ST_Event;
END_VAR
VAR
	fbGETSYSTEMTIME : GETSYSTEMTIME;
	stFileTime : T_FILETIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGETSYSTEMTIME(timeLoDW => stFileTime.dwLowDateTime,
				timeHiDW => stFileTime.dwHighDateTime);
				
stEvent.dtTimestamp := FILETIME_TO_DT(fileTime := stFileTime);]]></ST>
    </Implementation>
    <LineIds Name="UpdateEventTimestampWithSystemTime">
      <LineId Id="7" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="16" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>